services:
  data-processor-migrations:
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    command: alembic upgrade head
    env_file:
      - ../.env.example

  data-processor-worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    command: python -m data_processor.main
    env_file:
      - ../.env.example
